"""Configuração central do projeto."""

from .parameters import (
    DEFAULT_RESULTS_CSV,
    DEFAULT_HEURISTIC,
    DEFAULT_TIMEOUT_SECONDS,
    HEURISTIC_OPTIONS,
    INSTANCE_COUNT,
    INSTANCE_DIRECTORY,
    INSTANCE_FILE_PATTERN,
    PROJECT_ROOT,
    TIME_LIMIT_MS,
    TIME_LIMIT_SECONDS,
)

__all__ = [
    'PROJECT_ROOT',
    'INSTANCE_COUNT',
    'INSTANCE_DIRECTORY',
    'TIME_LIMIT_MS',
    'TIME_LIMIT_SECONDS',
    'DEFAULT_TIMEOUT_SECONDS',
    'DEFAULT_HEURISTIC',
    'HEURISTIC_OPTIONS',
    'DEFAULT_RESULTS_CSV',
    'INSTANCE_FILE_PATTERN',
]
